### ISSUE TITLE
db_writer is too restrictive

### ISSUE THREAD

**Issue by romanchyla** [adsabs/ADSDeploy#34]
it insists having all parameters, when application/environment are the only needed 

(and maybe not even those, if we want to send generic messages - well, probably we don't wnat)

**Comment by jonnybazookatone** [comment]
I think you mean something slightly different. It doesn't insist on having all the parameters, but limits the possibility of updating to a set of known parameters. It's more restrictive than insistent, specifically:

https://github.com/adsabs/ADSDeploy/blob/master/ADSDeploy/pipeline/db_writer.py#L85

```python
for attr in allowed_attr:
  try:
    setattr(deployment, attr, result[attr])
  except KeyError:
    continue
```

But we can remove this and let it be more flexible.
